In [1]:
import pandas as pd
import matplotlib.pyplot as plt
%matplotlib inline
import seaborn as sns

In [42]:
delivery = pd.read_csv('deliveries.csv')
match = pd.read_csv('matches.csv')
type(data)

pandas.core.frame.DataFrame

In [48]:
delivery.head()

,match_id,inning,batting_team,bowling_team,over,ball,batsman,non_striker,bowler,is_super_over,...,bye_runs,legbye_runs,noball_runs,penalty_runs,batsman_runs,extra_runs,total_runs,player_dismissed,dismissal_kind,fielder
0,1,1,Sunrisers Hyderabad,Royal Challengers Bangalore,1,1,DA Warner,S Dhawan,TS Mills,0,...,0,0,0,0,0,0,0,NaN,NaN,NaN
1,1,1,Sunrisers Hyderabad,Royal Challengers Bangalore,1,2,DA Warner,S Dhawan,TS Mills,0,...,0,0,0,0,0,0,0,NaN,NaN,NaN
2,1,1,Sunrisers Hyderabad,Royal Challengers Bangalore,1,3,DA Warner,S Dhawan,TS Mills,0,...,0,0,0,0,4,0,4,NaN,NaN,NaN
3,1,1,Sunrisers Hyderabad,Royal Challengers Bangalore,1,4,DA Warner,S Dhawan,TS Mills,0,...,0,0,0,0,0,0,0,NaN,NaN,NaN
4,1,1,Sunrisers Hyderabad,Royal Challengers Bangalore,1,5,DA Warner,S Dhawan,TS Mills,0,...,0,0,0,0,0,2,2,NaN,NaN,NaN

In [49]:
match.head()

,id,season,city,date,team1,team2,toss_winner,toss_decision,result,dl_applied,winner,win_by_runs,win_by_wickets,player_of_match,venue,umpire1,umpire2,umpire3
0,1,2017,Hyderabad,2017-04-05,Sunrisers Hyderabad,Royal Challengers Bangalore,Royal Challengers Bangalore,field,normal,0,Sunrisers Hyderabad,35,0,Yuvraj Singh,"Rajiv Gandhi International Stadium, Uppal",AY Dandekar,NJ Llong,NaN
1,2,2017,Pune,2017-04-06,Mumbai Indians,Rising Pune Supergiant,Rising Pune Supergiant,field,normal,0,Rising Pune Supergiant,0,7,SPD Smith,Maharashtra Cricket Association Stadium,A Nand Kishore,S Ravi,NaN
2,3,2017,Rajkot,2017-04-07,Gujarat Lions,Kolkata Knight Riders,Kolkata Knight Riders,field,normal,0,Kolkata Knight Riders,0,10,CA Lynn,Saurashtra Cricket Association Stadium,Nitin Menon,CK Nandan,NaN
3,4,2017,Indore,2017-04-08,Rising Pune Supergiant,Kings XI Punjab,Kings XI Punjab,field,normal,0,Kings XI Punjab,0,6,GJ Maxwell,Holkar Cricket Stadium,AK Chaudhary,C Shamshuddin,NaN
4,5,2017,Bangalore,2017-04-08,Royal Challengers Bangalore,Delhi Daredevils,Royal Challengers Bangalore,bat,normal,0,Royal Challengers Bangalore,15,0,KM Jadhav,M Chinnaswamy Stadium,NaN,NaN,NaN

In [123]:
ss = match.query('toss_winner == winner & toss_decision == "field"')['winner']
ss.value_counts()

Kolkata Knight Riders          38
Royal Challengers Bangalore    32
Mumbai Indians                 31
Kings XI Punjab                29
Rajasthan Royals               27
Chennai Super Kings            27
Delhi Daredevils               24
Sunrisers Hyderabad            15
Gujarat Lions                  10
Deccan Chargers                 8
Delhi Capitals                  6
Rising Pune Supergiant          5
Kochi Tuskers Kerala            4
Rising Pune Supergiants         3
Name: winner, dtype: int64

In [131]:
#sns.countplot(x='toss_decision', data=match)
#sns.countplot(x='venue', data=match)
#sns.jointplot(x='toss_decision', y='venue', data=match)
match['player_of_match'].value_counts()

CH Gayle             21
AB de Villiers       20
RG Sharma            17
MS Dhoni             17
DA Warner            17
YK Pathan            16
SR Watson            15
SK Raina             14
G Gambhir            13
AM Rahane            12
V Kohli              12
MEK Hussey           12
V Sehwag             11
DR Smith             11
AD Russell           11
A Mishra             11
KA Pollard           10
JH Kallis            10
SP Narine             9
SE Marsh              9
AT Rayudu             9
SR Tendulkar          8
UT Yadav              8
RA Jadeja             8
Harbhajan Singh       8
AC Gilchrist          7
Rashid Khan           7
RV Uthappa            7
BJ Hodge              6
A Nehra               6
                     ..
S Aravind             1
GD McGrath            1
Mustafizur Rahman     1
YS Chahal             1
MS Gony               1
M Ur Rahman           1
Washington Sundar     1
DJG Sammy             1
MR Marsh              1
K Paul                1
J Botha               1
KK Cooper             1
RJ Harris             1
P Parameswaran        1
M Kartik              1
A Singh               1
MS Bisla              1
JD Ryder              1
J Theron              1
Umar Gul              1
MD Mishra             1
LR Shukla             1
P Shaw                1
LH Ferguson           1
R Bhatia              1
SM Katich             1
R McLaren             1
SW Billings           1
PP Ojha               1
J Archer              1
Name: player_of_match, Length: 226, dtype: int64

In [ ]:
d = {
    'Sunrisers Hyderabad':0,
    'Rising Pune Supergiant':0,
    'Kolkata Knight Riders':0,
    'Kings XI Punjab':0,
    'Mumbai Indians':0,
    'Delhi Daredevils':0,
    'Gujarat Lions':0,
    'Royal Challengers Bangalore':0,
    'Chennai Super Kings':0,
    'Rajasthan Royals':0,
    'Deccan Chargers':0,
    'Kochi Tuskers Kerala':0,
    'Pune Warriors':0,
    nan:0,
    'Rising Pune Supergiants':0,
    'Delhi Capitals':0
    }

In [46]:
data.query('match_id =={} & inning == {}'.format(1,1))['total_runs'].sum()

207

,match_id,inning,batting_team,bowling_team,over,ball,batsman,non_striker,bowler,is_super_over,...,bye_runs,legbye_runs,noball_runs,penalty_runs,batsman_runs,extra_runs,total_runs,player_dismissed,dismissal_kind,fielder
0,1,1,Sunrisers Hyderabad,Royal Challengers Bangalore,1,1,DA Warner,S Dhawan,TS Mills,0,...,0,0,0,0,0,0,0,NaN,NaN,NaN
1,1,1,Sunrisers Hyderabad,Royal Challengers Bangalore,1,2,DA Warner,S Dhawan,TS Mills,0,...,0,0,0,0,0,0,0,NaN,NaN,NaN
2,1,1,Sunrisers Hyderabad,Royal Challengers Bangalore,1,3,DA Warner,S Dhawan,TS Mills,0,...,0,0,0,0,4,0,4,NaN,NaN,NaN
3,1,1,Sunrisers Hyderabad,Royal Challengers Bangalore,1,4,DA Warner,S Dhawan,TS Mills,0,...,0,0,0,0,0,0,0,NaN,NaN,NaN
4,1,1,Sunrisers Hyderabad,Royal Challengers Bangalore,1,5,DA Warner,S Dhawan,TS Mills,0,...,0,0,0,0,0,2,2,NaN,NaN,NaN
5,1,1,Sunrisers Hyderabad,Royal Challengers Bangalore,1,6,S Dhawan,DA Warner,TS Mills,0,...,0,0,0,0,0,0,0,NaN,NaN,NaN
6,1,1,Sunrisers Hyderabad,Royal Challengers Bangalore,1,7,S Dhawan,DA Warner,TS Mills,0,...,0,1,0,0,0,1,1,NaN,NaN,NaN
7,1,1,Sunrisers Hyderabad,Royal Challengers Bangalore,2,1,S Dhawan,DA Warner,A Choudhary,0,...,0,0,0,0,1,0,1,NaN,NaN,NaN
8,1,1,Sunrisers Hyderabad,Royal Challengers Bangalore,2,2,DA Warner,S Dhawan,A Choudhary,0,...,0,0,0,0,4,0,4,NaN,NaN,NaN
9,1,1,Sunrisers Hyderabad,Royal Challengers Bangalore,2,3,DA Warner,S Dhawan,A Choudhary,0,...,0,0,1,0,0,1,1,NaN,NaN,NaN
10,1,1,Sunrisers Hyderabad,Royal Challengers Bangalore,2,4,DA Warner,S Dhawan,A Choudhary,0,...,0,0,0,0,6,0,6,NaN,NaN,NaN
11,1,1,Sunrisers Hyderabad,Royal Challengers Bangalore,2,5,DA Warner,S Dhawan,A Choudhary,0,...,0,0,0,0,0,0,0,DA Warner,caught,Mandeep Singh
12,1,1,Sunrisers Hyderabad,Royal Challengers Bangalore,2,6,MC Henriques,S Dhawan,A Choudhary,0,...,0,0,0,0,0,0,0,NaN,NaN,NaN
13,1,1,Sunrisers Hyderabad,Royal Challengers Bangalore,2,7,MC Henriques,S Dhawan,A Choudhary,0,...,0,0,0,0,4,0,4,NaN,NaN,NaN
14,1,1,Sunrisers Hyderabad,Royal Challengers Bangalore,3,1,S Dhawan,MC Henriques,TS Mills,0,...,0,0,0,0,1,0,1,NaN,NaN,NaN
15,1,1,Sunrisers Hyderabad,Royal Challengers Bangalore,3,2,MC Henriques,S Dhawan,TS Mills,0,...,0,0,0,0,0,0,0,NaN,NaN,NaN
16,1,1,Sunrisers Hyderabad,Royal Challengers Bangalore,3,3,MC Henriques,S Dhawan,TS Mills,0,...,0,0,0,0,0,0,0,NaN,NaN,NaN
17,1,1,Sunrisers Hyderabad,Royal Challengers Bangalore,3,4,MC Henriques,S Dhawan,TS Mills,0,...,0,0,0,0,3,0,3,NaN,NaN,NaN
18,1,1,Sunrisers Hyderabad,Royal Challengers Bangalore,3,5,S Dhawan,MC Henriques,TS Mills,0,...,0,0,0,0,1,0,1,NaN,NaN,NaN
19,1,1,Sunrisers Hyderabad,Royal Challengers Bangalore,3,6,MC Henriques,S Dhawan,TS Mills,0,...,0,0,0,0,1,0,1,NaN,NaN,NaN
20,1,1,Sunrisers Hyderabad,Royal Challengers Bangalore,4,1,MC Henriques,S Dhawan,YS Chahal,0,...,0,0,0,0,0,0,0,NaN,NaN,NaN
21,1,1,Sunrisers Hyderabad,Royal Challengers Bangalore,4,2,MC Henriques,S Dhawan,YS Chahal,0,...,0,0,0,0,1,0,1,NaN,NaN,NaN
22,1,1,Sunrisers Hyderabad,Royal Challengers Bangalore,4,3,S Dhawan,MC Henriques,YS Chahal,0,...,0,0,0,0,0,0,0,NaN,NaN,NaN
23,1,1,Sunrisers Hyderabad,Royal Challengers Bangalore,4,4,S Dhawan,MC Henriques,YS Chahal,0,...,0,0,0,0,1,0,1,NaN,NaN,NaN
24,1,1,Sunrisers Hyderabad,Royal Challengers Bangalore,4,5,MC Henriques,S Dhawan,YS Chahal,0,...,0,0,0,0,1,0,1,NaN,NaN,NaN
25,1,1,Sunrisers Hyderabad,Royal Challengers Bangalore,4,6,S Dhawan,MC Henriques,YS Chahal,0,...,0,0,0,0,1,0,1,NaN,NaN,NaN
26,1,1,Sunrisers Hyderabad,Royal Challengers Bangalore,5,1,S Dhawan,MC Henriques,S Aravind,0,...,0,0,0,0,1,0,1,NaN,NaN,NaN
27,1,1,Sunrisers Hyderabad,Royal Challengers Bangalore,5,2,MC Henriques,S Dhawan,S Aravind,0,...,0,0,0,0,1,0,1,NaN,NaN,NaN
28,1,1,Sunrisers Hyderabad,Royal Challengers Bangalore,5,3,S Dhawan,MC Henriques,S Aravind,0,...,0,0,0,0,1,0,1,NaN,NaN,NaN
29,1,1,Sunrisers Hyderabad,Royal Challengers Bangalore,5,4,MC Henriques,S Dhawan,S Aravind,0,...,0,0,0,0,2,0,2,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
178924,11415,1,Mumbai Indians,Chennai Super Kings,16,1,KA Pollard,HH Pandya,RA Jadeja,0,...,0,0,0,0,1,0,1,NaN,NaN,NaN
178925,11415,1,Mumbai Indians,Chennai Super Kings,16,2,HH Pandya,KA Pollard,RA Jadeja,0,...,0,0,0,0,0,0,0,NaN,NaN,NaN
178926,11415,1,Mumbai Indians,Chennai Super Kings,16,3,HH Pandya,KA Pollard,RA Jadeja,0,...,0,0,0,0,1,0,1,NaN,NaN,NaN
178927,11415,1,Mumbai Indians,Chennai Super Kings,16,4,KA Pollard,HH Pandya,RA Jadeja,0,...,0,0,0,0,4,0,4,NaN,NaN,NaN
178928,11415,1,Mumbai Indians,Chennai Super Kings,16,5,KA Pollard,HH Pandya,RA Jadeja,0,...,0,0,0,0,1,0,1,NaN,NaN,NaN
178929,11415,1,Mumbai Indians,Chennai Super Kings,16,6,HH Pandya,KA Pollard,RA Jadeja,0,...,0,0,0,0,1,0,1,NaN,NaN,NaN
178930,11415,1,Mumbai Indians,Chennai Super Kings,17,1,HH Pandya,KA Pollard,Imran Tahir,0,...,0,0,0,0,1,0,1,NaN,NaN,NaN
178931,11415,1,Mumbai Indians,Chennai Super Kings,17,2,KA Pollard,HH Pandya,Imran Tahir,0,...,0,0,0,0,1,0,1,NaN,NaN,NaN
178932,11415,1,Mumbai Indians,Chennai Super Kings,17,3,HH Pandya,KA Pollard,Imran Tahir,0,...,0,0,0,0,1,0,1,NaN,NaN,NaN
178933,11415,1,Mumbai Indians,Chennai Super Kings,17,4,KA Pollard,HH Pandya,Imran Tahir,0,...,0,0,0,0,0,0,0,NaN,NaN,NaN
178934,11415,1,Mumbai Indians,Chennai Super Kings,17,5,KA Pollard,HH Pandya,Imran Tahir,0,...,0,0,0,0,6,0,6,NaN,NaN,NaN
178935,11415,1,Mumbai Indians,Chennai Super Kings,17,6,KA Pollard,HH Pandya,Imran Tahir,0,...,0,0,0,0,1,0,1,NaN,NaN,NaN
178936,11415,1,Mumbai Indians,Chennai Super Kings,18,1,KA Pollard,HH Pandya,SN Thakur,0,...,0,0,0,0,1,0,1,NaN,NaN,NaN
178937,11415,1,Mumbai Indians,Chennai Super Kings,18,2,HH Pandya,KA Pollard,SN Thakur,0,...,0,0,0,0,1,0,1,NaN,NaN,NaN
178938,11415,1,Mumbai Indians,Chennai Super Kings,18,3,KA Pollard,HH Pandya,SN Thakur,0,...,0,0,0,0,6,0,6,NaN,NaN,NaN
178939,11415,1,Mumbai Indians,Chennai Super Kings,18,4,KA Pollard,HH Pandya,SN Thakur,0,...,0,0,0,0,1,0,1,NaN,NaN,NaN
178940,11415,1,Mumbai Indians,Chennai Super Kings,18,5,HH Pandya,KA Pollard,SN Thakur,0,...,0,0,0,0,6,0,6,NaN,NaN,NaN
178941,11415,1,Mumbai Indians,Chennai Super Kings,18,6,HH Pandya,KA Pollard,SN Thakur,0,...,0,0,0,0,1,0,1,NaN,NaN,NaN
178942,11415,1,Mumbai Indians,Chennai Super Kings,19,1,HH Pandya,KA Pollard,DL Chahar,0,...,0,0,0,0,4,0,4,NaN,NaN,NaN
178943,11415,1,Mumbai Indians,Chennai Super Kings,19,2,HH Pandya,KA Pollard,DL Chahar,0,...,0,0,0,0,0,0,0,HH Pandya,lbw,NaN
178944,11415,1,Mumbai Indians,Chennai Super Kings,19,3,RD Chahar,KA Pollard,DL Chahar,0,...,0,0,0,0,0,0,0,NaN,NaN,NaN
178945,11415,1,Mumbai Indians,Chennai Super Kings,19,4,RD Chahar,KA Pollard,DL Chahar,0,...,0,0,0,0,0,0,0,RD Chahar,caught,F du Plessis
178946,11415,1,Mumbai Indians,Chennai Super Kings,19,5,MJ McClenaghan,KA Pollard,DL Chahar,0,...,0,0,0,0,0,0,0,NaN,NaN,NaN
178947,11415,1,Mumbai Indians,Chennai Super Kings,19,6,MJ McClenaghan,KA Pollard,DL Chahar,0,...,0,0,0,0,0,0,0,NaN,NaN,NaN
178948,11415,1,Mumbai Indians,Chennai Super Kings,20,1,KA Pollard,MJ McClenaghan,DJ Bravo,0,...,0,0,0,0,0,0,0,NaN,NaN,NaN
178949,11415,1,Mumbai Indians,Chennai Super Kings,20,2,KA Pollard,MJ McClenaghan,DJ Bravo,0,...,0,0,0,0,0,0,0,NaN,NaN,NaN
178950,11415,1,Mumbai Indians,Chennai Super Kings,20,3,KA Pollard,MJ McClenaghan,DJ Bravo,0,...,0,0,0,0,0,0,0,NaN,NaN,NaN
178951,11415,1,Mumbai Indians,Chennai Super Kings,20,4,KA Pollard,MJ McClenaghan,DJ Bravo,0,...,0,0,0,0,1,0,1,MJ McClenaghan,run out,F du Plessis
178952,11415,1,Mumbai Indians,Chennai Super Kings,20,5,KA Pollard,JJ Bumrah,DJ Bravo,0,...,0,0,0,0,4,0,4,NaN,NaN,NaN
178953,11415,1,Mumbai Indians,Chennai Super Kings,20,6,KA Pollard,JJ Bumrah,DJ Bravo,0,...,0,0,0,0,4,0,4,NaN,NaN,NaN

In [38]:
score1=0
score2=0
srt1=""
str2=""
for i in data['match_id']:
    for j in data['inning']:
        if j==1:
            socre1 = data.query('match_id == {} & inning == {}'.format(i,1)).sum()
        else:
            score2 = data.query('match_id =={} & inning == {}'.format(i,2)).sum()
        print(max(score1, score2))

0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0

TypeError: '>' not supported between instances of 'str' and 'int'